let output=document.querySelector("#output");/*queryselector select the first result matches with css*/

//output.contentDocument.body.innerHTML="<h1>Welcome to WS<h1>"/*contentDocument property returns the Document object generated by a frame*/

//output.contentDocument.head.innerHTML="<style> h1{color:red}</style>"

//output.contentWindow.eval('let a=10; let b=20; alert(a+b)');/*contentWindow is used in javascript and eval is used for calculation means it puts javascript code into window and execute it*/

let allInput=document.querySelectorAll(".leftpart textarea");//querySelectorAll gives element in a node list

let htmlCode,cssCode,jsCode='';

allInput.forEach((el,index)=>{ //forEach() calls a function for each element in an array and,el represent the textarea and it also tells the index of textarea
    el.addEventListener("keyup",()=>{//addEventListener attaches an event handler to a document and keyup is just a name
        if(index==0){
            htmlCode=el.value;

        }
        if(index==1){
            cssCode=el.value;
            
        }
        if(index==2){
            jsCode=el.value;
        }
        output.contentDocument.body.innerHTML=htmlCode;
        output.contentDocument.head.innerHTML='<style>${cssCode}</style>';
        output.contentWindow.eval(jsCode);
})
})
